FROM python:3.7-alpine
COPY . /
WORKDIR /
RUN pip install -r requirements.txt
RUN pip install gunicorn
RUN pip install --upgrade setuptools
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install psycopg2 
EXPOSE 9999
CMD ["gunicorn", "-b", "0.0.0.0:9999", "app:app"]
